name: ⬆️ Upstream Sync

on:
  schedule:
    - cron: '0 3 * * *' # Todos los días a las 3am UTC
  workflow_dispatch:

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          persist-credentials: false

      - name: Set git config
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email '41898282+github-actions[bot]@users.noreply.github.com'

      - name: Pull upstream changes
        run: |
          git remote add upstream https://github.com/lobehub/lobe-chat.git
          git fetch upstream
          git merge upstream/main --allow-unrelated-histories --no-edit
          git push origin main
